export const BAGAGE_SECSold = [
  {
    id: "nl-acheter-bagages",
    ico: "🧳",
    bg: "#eef2ff",
    nm: "Bagages — à acheter",
    badge: { t: "Lié à Acheter", c: "b-pur" },
    note: {
      t: "Cette section affiche les articles de la liste Acheter. Coche un article ici ou dans Acheter pour le marquer comme emporté.",
      c: "n-grn",
    },
    items: [],
  },
  {
    id: "nl-hauts",
    ico: "👕",
    bg: "#eef2ff",
    nm: "Vêtements — hauts (déjà en ma possession)",
    badge: { t: "À emporter", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl1", t: "T-shirt blanc", d: "", s: "", g: ["req"] },
      { id: "nl3", t: "T-shirt noir", d: "", s: "", g: ["req"] },
      {
        id: "nl5",
        t: "Chemise classique bleu/blanc (mix)",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl6", t: "Chemise classique blanche", d: "", s: "", g: ["req"] },
      {
        id: "nl12",
        t: "T-shirt manches longues (1/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl13",
        t: "T-shirt manches longues (2/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl14",
        t: "T-shirt manches longues (3/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl15", t: "T-shirt de football", d: "", s: "", g: ["opt"] },
    ],
  },
  {
    id: "nl-bas",
    ico: "👖",
    bg: "#eef2ff",
    nm: "Vêtements — bas (déjà en ma possession)",
    badge: { t: "À emporter", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [{ id: "nl19", t: "Short de football", d: "", s: "", g: ["opt"] }],
  },
  {
    id: "nl-survetement-qamis",
    ico: "🧥",
    bg: "#eef2ff",
    nm: "Survêtement & Qamis",
    badge: { t: "À emporter", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl25", t: "Survêtement complet", d: "", s: "", g: ["req"] },
      { id: "nl26", t: "Qamis", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "nl-vestes-couvre-chef",
    ico: "🧢",
    bg: "#eef2ff",
    nm: "Vestes & couvre-chef",
    badge: { t: "À emporter", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl27", t: "Veste mi-saison", d: "", s: "", g: ["req"] },
      { id: "nl28", t: "Veste d'hiver", d: "", s: "", g: ["req"] },
      { id: "nl29", t: "Veste de sport noire", d: "", s: "", g: ["req"] },
      { id: "nl30", t: "Casquette bleue", d: "", s: "", g: ["opt"] },
      { id: "nl31", t: "Casquette verte", d: "", s: "", g: ["opt"] },
      { id: "nl32", t: "Casquette bordeaux", d: "", s: "", g: ["opt"] },
      { id: "nl33", t: "Bonnet", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "nl-electronique-perso",
    ico: "💻",
    bg: "#eef2ff",
    nm: "Électronique & effets personnels (déjà en ma possession)",
    badge: { t: "À emporter", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl37", t: "Laptop", d: "", s: "", g: ["req"] },
      { id: "nl38", t: "Sac à dos", d: "", s: "", g: ["req"] },
      { id: "nl39", t: "Clé USB (flash disque)", d: "", s: "", g: ["req"] },
      { id: "nl43", t: "Adaptateur secteur", d: "", s: "", g: ["req"] },
      { id: "nl44", t: "Prises multiples", d: "", s: "", g: ["req"] },
      { id: "nl45", t: "Chargeur", d: "", s: "", g: ["req"] },
      { id: "nl47", t: "Lunettes de soleil", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "nl-docs-admin",
    ico: "📄",
    bg: "#fff7e6",
    nm: "Documents administratifs",
    badge: { t: "Original + copie + scan", c: "b-amb" },
    note: {
      t: "Chaque diplôme/relevé doit être emporté en original ET en copie, et scanné/sauvegardé avant le départ.",
      c: "n-amb",
    },
    items: [
      { id: "nl49", t: "Baccalauréat (BAC)", d: "", s: "", g: ["req"] },
      { id: "nl50", t: "Relevé de notes du BAC", d: "", s: "", g: ["req"] },
      { id: "nl51", t: "Relevé de notes — L1", d: "", s: "", g: ["req"] },
      { id: "nl52", t: "Relevé de notes — L2", d: "", s: "", g: ["req"] },
      { id: "nl53", t: "Relevé de notes — L3", d: "", s: "", g: ["req"] },
      { id: "nl54", t: "Diplôme de Licence", d: "", s: "", g: ["req"] },
      { id: "nl55", t: "Relevé de notes — M1", d: "", s: "", g: ["req"] },
      { id: "nl56", t: "Relevé de notes — M2", d: "", s: "", g: ["req"] },
      { id: "nl57", t: "Diplôme de Master", d: "", s: "", g: ["req"] },
      {
        id: "nl58",
        t: "Annexe descriptive — Licence",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl59",
        t: "Annexe descriptive — Master",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl60", t: "Certificat TCF", d: "", s: "", g: ["req"] },
      { id: "nl61", t: "Papier de préinscription", d: "", s: "", g: ["req"] },
      { id: "nl62", t: "Bordereau de retrait", d: "", s: "", g: ["req"] },
      { id: "nl63", t: "Certificat de travail", d: "", s: "", g: ["req"] },
      { id: "nl64", t: "Lettres de recommandation", d: "", s: "", g: ["req"] },
      {
        id: "nl65",
        t: "Fiche familiale d'état civil",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl66",
        t: "Acte de naissance — moi",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl67",
        t: "Acte de naissance — mère",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl68",
        t: "Acte de naissance — père",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl69",
        t: "Acte de naissance — grand-père",
        d: "⚠ quantité non précisée — à confirmer combien d'exemplaires",
        s: "",
        g: ["opt"],
      },
      { id: "nl70", t: "Carte Visa AGB", d: "", s: "", g: ["req"] },
      { id: "nl71", t: "Permis de conduire", d: "", s: "", g: ["req"] },
      {
        id: "nl72",
        t: "Copies de tous les relevés et diplômes",
        d: "Un jeu complet de copies séparé des originaux",
        s: "",
        g: ["req"],
      },
      { id: "nl73", t: "Photos d'identité", d: "20 photos", s: "", g: ["req"] },
      {
        id: "nl74",
        t: "Tous les documents scannés",
        d: "Sauvegarde cloud + clé USB, séparée du sac à documents",
        s: "",
        g: ["req"],
      },
      { id: "nl75", t: "Photo de famille", d: "", s: "", g: ["opt"] },
    ],
  },
  {
    id: "nl-docs-medicaux",
    ico: "🩺",
    bg: "#fff7e6",
    nm: "Dossier militaire & médical",
    badge: { t: "À emporter", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "nl76", t: "Radio EFR (asthme)", d: "", s: "", g: ["req"] },
      { id: "nl77", t: "Radio de l'épaule", d: "", s: "", g: ["req"] },
      { id: "nl78", t: "Papier de l'épaule", d: "", s: "", g: ["req"] },
      { id: "nl79", t: "Papier ophtalmo", d: "", s: "", g: ["req"] },
      { id: "nl80", t: "Ordonnance lunettes", d: "", s: "", g: ["req"] },
    ],
  },
];

export const ACHETER_SECSold = [
  {
    id: "nl-vetements-acheter",
    ico: "👕",
    bg: "#fff1f0",
    nm: "Vêtements — à acheter",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: {
      t: "Les articles de cette section sont liés à la section Bagages — à acheter.",
      c: "n-amb",
    },
    items: [
      { id: "nl16", t: "Jean noir (1/2)", d: "", s: "", g: ["buy"], est: 6000 },
      { id: "nl17", t: "Jean noir (2/2)", d: "", s: "", g: ["buy"], est: 6000 },
      {
        id: "nl18",
        t: "Jean crème/beige",
        d: "",
        s: "",
        g: ["buy"],
        est: 6000,
      },
      { id: "nl2", t: "T-shirt bleu", d: "", s: "", g: ["buy"], est: 2300 },
      { id: "nl4", t: "T-shirt beige", d: "", s: "", g: ["buy"], est: 2300 },
      {
        id: "nl7",
        t: "Maillot de peau noir",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      {
        id: "nl8",
        t: "Maillot de peau gris",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      {
        id: "nl9",
        t: "Maillot de peau blanc (1/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      {
        id: "nl10",
        t: "Maillot de peau blanc (2/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      {
        id: "nl11",
        t: "Maillot de peau blanc (3/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      {
        id: "nl20",
        t: "Short pour dormir",
        d: "",
        s: "",
        g: ["buy"],
        est: 1200,
      },
      {
        id: "nl21",
        t: "Sous-vêtements",
        d: "8 unités à 650 DA",
        s: "",
        g: ["buy"],
        est: 5200,
      },
      {
        id: "nl22",
        t: "Chaussettes",
        d: "12 paires à 100 DA",
        s: "",
        g: ["buy"],
        est: 1200,
      },
      {
        id: "nl23a",
        t: "Survêtement pour dormir",
        d: "",
        s: "",
        g: ["buy"],
        est: 3500,
      },
      {
        id: "nl23b",
        t: "T-shirt manches longues pour dormir",
        d: "",
        s: "",
        g: ["buy"],
        est: 2500,
      },
      {
        id: "nl24",
        t: "T-shirt manches courtes pour dormir",
        d: "",
        s: "",
        g: ["buy"],
        est: 1000,
      },
    ],
  },
  {
    id: "nl-chaussures-acheter",
    ico: "👟",
    bg: "#fff1f0",
    nm: "Chaussures — à acheter",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: {
      t: "Les articles de cette section sont liés à la section Bagages — à acheter.",
      c: "n-amb",
    },
    items: [
      {
        id: "nl34",
        t: "Chaussures Mizuno beige",
        d: "",
        s: "",
        g: ["buy"],
        est: 12000,
      },
      {
        id: "nl35",
        t: "Chaussures blanches (usage quotidien)",
        d: "",
        s: "",
        g: ["buy"],
        est: 8000,
      },
      {
        id: "nl36",
        t: "Chaussures noires de randonnée/marche",
        d: "",
        s: "",
        g: ["buy"],
        est: 3400,
      },
      {
        id: "nl130",
        t: "Claquettes / tongs",
        d: "⚠ ajouté, prix non précisé — estimation à confirmer",
        s: "",
        g: ["buy"],
        est: 1500,
      },
    ],
  },
  {
    id: "nl-electronique-acheter",
    ico: "🔌",
    bg: "#fff1f0",
    nm: "Électronique — à acheter",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: {
      t: "Les articles de cette section sont liés à la section Bagages — à acheter.",
      c: "n-amb",
    },
    items: [
      { id: "nl46", t: "Powerbank", d: "", s: "", g: ["buy"], est: 4000 },
      { id: "nl40", t: "Écouteurs", d: "", s: "", g: ["buy"], est: 5000 },
      { id: "nl41", t: "Casque audio", d: "", s: "", g: ["buy"], est: 6000 },
      {
        id: "nl42",
        t: "Disque dur externe 1 To",
        d: "",
        s: "",
        g: ["buy"],
        est: 9000,
      },
      {
        id: "nl48",
        t: "Lunettes de vue (médicales)",
        d: "Visite médicale + lunettes",
        s: "",
        g: ["buy"],
        est: 2500,
      },
    ],
  },
  {
    id: "nl-hygiene-acheter",
    ico: "🧴",
    bg: "#fff1f0",
    nm: "Hygiène & soins — à acheter",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: {
      t: "Les articles de cette section sont liés à la section Bagages — à acheter.",
      c: "n-amb",
    },
    items: [
      {
        id: "nl90a",
        t: "Déodorant stick (1/2)",
        d: "",
        s: "",
        g: ["buy"],
        est: 750,
      },
      {
        id: "nl90b",
        t: "Déodorant stick (2/2)",
        d: "",
        s: "",
        g: ["buy"],
        est: 750,
      },
      { id: "nl91", t: "Gel douche", d: "", s: "", g: ["buy"], est: 900 },
      { id: "nl92", t: "Shampooing", d: "", s: "", g: ["buy"], est: 900 },
      { id: "nl93", t: "Après-shampooing", d: "", s: "", g: ["buy"], est: 900 },
      {
        id: "nl94",
        t: "Tondeuse à cheveux",
        d: "",
        s: "",
        g: ["buy"],
        est: 4000,
      },
      { id: "nl95", t: "Ciseaux", d: "", s: "", g: ["buy"], est: 500 },
      {
        id: "nl96",
        t: "Rasoir (coupe-choux / manche)",
        d: "",
        s: "",
        g: ["buy"],
        est: 1500,
      },
      {
        id: "nl97",
        t: "Lames de rechange pour le rasoir",
        d: "",
        s: "",
        g: ["buy"],
        est: 300,
      },
      {
        id: "nl98a",
        t: "Rasoirs jetables normaux — paquet 1/2",
        d: "",
        s: "",
        g: ["buy"],
        est: 800,
      },
      {
        id: "nl98b",
        t: "Rasoirs jetables normaux — paquet 2/2",
        d: "",
        s: "",
        g: ["buy"],
        est: 800,
      },
      {
        id: "nl99",
        t: "Masque cheveux Cilane bio",
        d: "",
        s: "",
        g: ["buy"],
        est: 1800,
      },
      {
        id: "nl100a",
        t: "Crème cheveux (1/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 400,
      },
      {
        id: "nl100b",
        t: "Crème cheveux (2/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 200,
      },
      {
        id: "nl100c",
        t: "Crème cheveux (3/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 200,
      },
      {
        id: "nl101a",
        t: "Gel cheveux fixation (1/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 250,
      },
      {
        id: "nl101b",
        t: "Gel cheveux fixation (2/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 250,
      },
      {
        id: "nl101c",
        t: "Gel cheveux fixation (3/3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 250,
      },
      {
        id: "nl102",
        t: "Crème dépilatoire corps",
        d: "6 unités à 200 DA",
        s: "",
        g: ["buy"],
        est: 1200,
      },
      { id: "nl103", t: "Coupe-ongles", d: "", s: "", g: ["buy"], est: 400 },
      {
        id: "nl104",
        t: "Brosse à cheveux ronde",
        d: "",
        s: "",
        g: ["buy"],
        est: 500,
      },
      {
        id: "nl105",
        t: "Brosse à cheveux normale",
        d: "",
        s: "",
        g: ["buy"],
        est: 600,
      },
      { id: "nl106", t: "Déodorant (1/2)", d: "", s: "", g: ["buy"], est: 500 },
      { id: "nl107", t: "Déodorant (2/2)", d: "", s: "", g: ["buy"], est: 500 },
      { id: "nl108", t: "Parfum (1/4)", d: "", s: "", g: ["buy"], est: 600 },
      { id: "nl109", t: "Parfum (2/4)", d: "", s: "", g: ["buy"], est: 600 },
      { id: "nl110", t: "Parfum (3/4)", d: "", s: "", g: ["buy"], est: 600 },
      { id: "nl111", t: "Parfum (4/4)", d: "", s: "", g: ["buy"], est: 600 },
      {
        id: "nl112",
        t: "Kassa (gant de kessa)",
        d: "",
        s: "",
        g: ["buy"],
        est: 300,
      },
      { id: "nl120", t: "Brosse à dents", d: "", s: "", g: ["buy"], est: 300 },
      { id: "nl121", t: "Dentifrice", d: "", s: "", g: ["buy"], est: 400 },
      {
        id: "nl122",
        t: "Serviette de corps",
        d: "",
        s: "",
        g: ["buy"],
        est: 1500,
      },
      {
        id: "nl123",
        t: "Serviette de visage",
        d: "",
        s: "",
        g: ["buy"],
        est: 700,
      },
      { id: "nl124", t: "Crème solaire", d: "", s: "", g: ["buy"], est: 1500 },
    ],
  },
  {
    id: "nl-bagages-acheter",
    ico: "🧳",
    bg: "#fff1f0",
    nm: "Bagages (valises) — à acheter",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "Norme Air Algérie", c: "b-amb" },
    note: {
      t: "Norme bagages Air Algérie (classe économique, vol international) : 1 bagage en soute jusqu'à 23 kg + 1 bagage cabine jusqu'à 10 kg. Vérifie les dimensions max autorisées sur ton billet avant l'achat.",
      c: "n-amb",
    },
    items: [
      {
        id: "nl113",
        t: "Valise soute — 23 kg",
        d: "",
        s: "",
        g: ["buy"],
        est: 13000,
      },
      {
        id: "nl114",
        t: "Sac cabine — 10 kg",
        d: "",
        s: "",
        g: ["buy"],
        est: 4000,
      },
    ],
  },
  {
    id: "nl-divers-suggeres",
    ico: "✏️",
    bg: "#fff1f0",
    nm: "Divers suggérés (non mentionnés, souvent oubliés)",
    linkedSectionId: "nl-acheter-bagages",
    badge: { t: "Vérifie si utile", c: "b-pur" },
    note: {
      t: "Pas dans ta description d'origine — supprime avec le × si inutile.",
      c: "n-amb",
    },
    items: [
      {
        id: "nl125",
        t: "Petite pharmacie (paracétamol, pansements)",
        d: "⚠ ajouté",
        s: "",
        g: ["buy"],
        est: 1500,
      },
      {
        id: "nl126",
        t: "Parapluie",
        d: "⚠ ajouté — climat de Besançon",
        s: "",
        g: ["buy"],
        est: 1500,
      },
      {
        id: "nl127",
        t: "Caleçons longs (sous-vêtement thermique)",
        d: "⚠ ajouté — utile pour l'hiver à Besançon",
        s: "",
        g: ["buy"],
        est: 2000,
      },
      {
        id: "nl128",
        t: "Sajjada (tapis de prière)",
        d: "⚠ ajouté",
        s: "",
        g: ["buy"],
        est: 2500,
      },
      {
        id: "nl129",
        t: "Cadenas",
        d: "⚠ ajouté — casiers/laverie résidence",
        s: "",
        g: ["buy"],
        est: 800,
      },
    ],
  },
];

// ============================================================================
// Liste de bagages — v4. Tout est réuni dans une seule liste (BAGAGE_SECS).
// Rien n'est pré-marqué "à acheter" — utilise le ticket 🛒 dans l'app sur
// chaque élément toi-même pour construire ta liste Acheter au fur et à
// mesure. Les prix que tu avais donnés sont gardés en note (d) sur chaque
// élément concerné, pour que tu les aies sous la main au moment de cocher
// "à acheter" (l'app te redemandera confirmation du prix à ce moment-là).
// ============================================================================

const BAGAGE_SECS_v4 = [
  {
    id: "nl-hauts",
    ico: "👕",
    bg: "#eef2ff",
    nm: "Vêtements — hauts",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl1", t: "T-shirt blanc", d: "", s: "", g: ["req"] },
      {
        id: "nl2",
        t: "T-shirt bleu",
        d: "Prix estimé : 2300 DA",
        s: "",
        g: ["req"],
      },
      { id: "nl3", t: "T-shirt noir", d: "", s: "", g: ["req"] },
      {
        id: "nl4",
        t: "T-shirt beige",
        d: "Prix estimé : 2300 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl5",
        t: "Chemise classique bleu/blanc (mix)",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl6", t: "Chemise classique blanche", d: "", s: "", g: ["req"] },
      {
        id: "nl7",
        t: "Maillot de peau noir",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl8",
        t: "Maillot de peau gris",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl9",
        t: "Maillot de peau blanc (1/3)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl10",
        t: "Maillot de peau blanc (2/3)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl11",
        t: "Maillot de peau blanc (3/3)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl12",
        t: "T-shirt manches longues (1/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl13",
        t: "T-shirt manches longues (2/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl14",
        t: "T-shirt manches longues (3/3)",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl15", t: "T-shirt de football", d: "", s: "", g: ["opt"] },
    ],
  },
  {
    id: "nl-bas",
    ico: "👖",
    bg: "#eef2ff",
    nm: "Vêtements — bas",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      {
        id: "nl16",
        t: "Jean noir (1/2)",
        d: "Prix estimé : 6000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl17",
        t: "Jean noir (2/2)",
        d: "Prix estimé : 6000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl18",
        t: "Jean crème/beige",
        d: "Prix estimé : 6000 DA",
        s: "",
        g: ["req"],
      },
      { id: "nl19", t: "Short de football", d: "", s: "", g: ["opt"] },
      {
        id: "nl20",
        t: "Short pour dormir",
        d: "Prix estimé : 1200 DA",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-sousvetements-nuit",
    ico: "🩲",
    bg: "#eef2ff",
    nm: "Sous-vêtements, chaussettes & tenues de nuit",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      {
        id: "nl21",
        t: "Sous-vêtements",
        d: "8 unités — prix estimé : 650 DA/unité",
        s: "",
        g: ["req"],
      },
      {
        id: "nl22",
        t: "Chaussettes",
        d: "12 paires — prix estimé : 100 DA/paire",
        s: "",
        g: ["req"],
      },
      {
        id: "nl23a",
        t: "Survêtement pour dormir",
        d: "Prix estimé : 3500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl23b",
        t: "T-shirt manches longues pour dormir",
        d: "Prix estimé : 2500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl24",
        t: "T-shirt manches courtes pour dormir",
        d: "Prix estimé : 1000 DA",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-survetement-qamis",
    ico: "🧥",
    bg: "#eef2ff",
    nm: "Survêtement, Qamis & vestes",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl25", t: "Survêtement complet", d: "", s: "", g: ["req"] },
      { id: "nl26", t: "Qamis", d: "", s: "", g: ["req"] },
      { id: "nl27", t: "Veste mi-saison", d: "", s: "", g: ["req"] },
      { id: "nl28", t: "Veste d'hiver", d: "", s: "", g: ["req"] },
      { id: "nl29", t: "Veste de sport noire", d: "", s: "", g: ["req"] },
      { id: "nl30", t: "Casquette bleue", d: "", s: "", g: ["opt"] },
      { id: "nl31", t: "Casquette verte", d: "", s: "", g: ["opt"] },
      { id: "nl32", t: "Casquette bordeaux", d: "", s: "", g: ["opt"] },
      { id: "nl33", t: "Bonnet", d: "", s: "", g: ["req"] },
      {
        id: "nl140",
        t: "Écharpe",
        d: "⚠ ajouté — utile pour l'hiver à Besançon",
        s: "",
        g: ["req"],
      },
      {
        id: "nl141",
        t: "Gants",
        d: "⚠ à vérifier si déjà en ta possession",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-chaussures",
    ico: "👟",
    bg: "#eef2ff",
    nm: "Chaussures",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      {
        id: "nl34",
        t: "Chaussures Mizuno beige",
        d: "Prix estimé : 12000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl35",
        t: "Chaussures blanches (usage quotidien)",
        d: "Prix estimé : 8000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl36",
        t: "Chaussures noires de randonnée/marche",
        d: "Prix estimé : 3400 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl130",
        t: "Claquettes / tongs",
        d: "⚠ ajouté, prix non précisé",
        s: "",
        g: ["opt"],
      },
    ],
  },
  {
    id: "nl-electronique-perso",
    ico: "💻",
    bg: "#eef2ff",
    nm: "Électronique & effets personnels",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      { id: "nl37", t: "Laptop", d: "", s: "", g: ["req"] },
      { id: "nl38", t: "Sac à dos", d: "", s: "", g: ["req"] },
      { id: "nl39", t: "Clé USB (flash disque)", d: "", s: "", g: ["req"] },
      {
        id: "nl40",
        t: "Écouteurs",
        d: "Prix estimé : 5000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl41",
        t: "Casque audio",
        d: "Prix estimé : 6000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl42",
        t: "Disque dur externe 1 To",
        d: "Prix estimé : 9000 DA",
        s: "",
        g: ["req"],
      },
      { id: "nl43", t: "Adaptateur secteur", d: "", s: "", g: ["req"] },
      { id: "nl44", t: "Prises multiples", d: "", s: "", g: ["req"] },
      { id: "nl45", t: "Chargeur", d: "", s: "", g: ["req"] },
      {
        id: "nl46",
        t: "Powerbank",
        d: "Prix estimé : 4000 DA",
        s: "",
        g: ["req"],
      },
      { id: "nl47", t: "Lunettes de soleil", d: "", s: "", g: ["req"] },
      {
        id: "nl48",
        t: "Lunettes de vue (médicales)",
        d: "Visite médicale + lunettes — prix estimé : 2500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl142",
        t: "Étui de rechange pour lunettes",
        d: "⚠ ajouté",
        s: "",
        g: ["opt"],
      },
      { id: "nl143", t: "Piles de rechange", d: "⚠ ajouté", s: "", g: ["opt"] },
    ],
  },
  {
    id: "nl-hygiene",
    ico: "🧴",
    bg: "#eef2ff",
    nm: "Hygiène & soins",
    badge: { t: "À emporter", c: "b-blu" },
    hasPrices: true,
    note: { t: "", c: "n-grn" },
    items: [
      {
        id: "nl90a",
        t: "Déodorant stick (1/2)",
        d: "Prix estimé : 750 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl90b",
        t: "Déodorant stick (2/2)",
        d: "Prix estimé : 750 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl91",
        t: "Gel douche",
        d: "Prix estimé : 900 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl92",
        t: "Shampooing",
        d: "Prix estimé : 900 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl93",
        t: "Après-shampooing",
        d: "Prix estimé : 900 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl94",
        t: "Tondeuse à cheveux",
        d: "Prix estimé : 4000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl95",
        t: "Ciseaux",
        d: "Prix estimé : 500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl96",
        t: "Rasoir (coupe-choux / manche)",
        d: "Prix estimé : 1500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl97",
        t: "Lames de rechange pour le rasoir",
        d: "Prix estimé : 300 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl98a",
        t: "Rasoirs jetables normaux — paquet 1/2",
        d: "Prix estimé : 800 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl98b",
        t: "Rasoirs jetables normaux — paquet 2/2",
        d: "Prix estimé : 800 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl99",
        t: "Masque cheveux Cilane bio",
        d: "Prix estimé : 1800 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl100a",
        t: "Crème cheveux (1/3)",
        d: "Prix estimé : 400 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl100b",
        t: "Crème cheveux (2/3)",
        d: "Prix estimé : 200 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl100c",
        t: "Crème cheveux (3/3)",
        d: "Prix estimé : 200 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl101a",
        t: "Gel cheveux fixation (1/3)",
        d: "Prix estimé : 250 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl101b",
        t: "Gel cheveux fixation (2/3)",
        d: "Prix estimé : 250 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl101c",
        t: "Gel cheveux fixation (3/3)",
        d: "Prix estimé : 250 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl102",
        t: "Crème dépilatoire corps",
        d: "6 unités — prix estimé : 200 DA/unité",
        s: "",
        g: ["req"],
      },
      {
        id: "nl103",
        t: "Coupe-ongles",
        d: "Prix estimé : 400 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl104",
        t: "Brosse à cheveux ronde",
        d: "Prix estimé : 500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl105",
        t: "Brosse à cheveux normale",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl106",
        t: "Déodorant (1/2)",
        d: "Prix estimé : 500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl107",
        t: "Déodorant (2/2)",
        d: "Prix estimé : 500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl108",
        t: "Parfum (1/4)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl109",
        t: "Parfum (2/4)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl110",
        t: "Parfum (3/4)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl111",
        t: "Parfum (4/4)",
        d: "Prix estimé : 600 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl112",
        t: "Kassa (gant de kessa)",
        d: "Prix estimé : 300 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl120",
        t: "Brosse à dents",
        d: "Prix estimé : 300 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl121",
        t: "Dentifrice",
        d: "Prix estimé : 400 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl122",
        t: "Serviette de corps",
        d: "Prix estimé : 1500 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl123",
        t: "Serviette de visage",
        d: "Prix estimé : 700 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl124",
        t: "Crème solaire",
        d: "Prix estimé : 1500 DA",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-bagages",
    ico: "🧳",
    bg: "#eef2ff",
    nm: "Bagages (valises)",
    badge: { t: "Norme Air Algérie", c: "b-blu" },
    hasPrices: true,
    note: {
      t: "Norme bagages Air Algérie (classe économique, vol international) : 1 bagage en soute jusqu'à 23 kg + 1 bagage cabine jusqu'à 10 kg. Vérifie les dimensions max autorisées sur ton billet avant l'achat.",
      c: "n-grn",
    },
    items: [
      {
        id: "nl113",
        t: "Valise soute — 23 kg",
        d: "Prix estimé : 13000 DA",
        s: "",
        g: ["req"],
      },
      {
        id: "nl114",
        t: "Sac cabine — 10 kg",
        d: "Prix estimé : 4000 DA",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-docs-admin",
    ico: "📄",
    bg: "#fff7e6",
    nm: "Documents administratifs",
    badge: { t: "Original + copie + scan", c: "b-amb" },
    note: {
      t: "Chaque diplôme/relevé doit être emporté en original ET en copie, et scanné/sauvegardé avant le départ.",
      c: "n-amb",
    },
    items: [
      { id: "nl49", t: "Baccalauréat (BAC)", d: "", s: "", g: ["req"] },
      { id: "nl50", t: "Relevé de notes du BAC", d: "", s: "", g: ["req"] },
      { id: "nl51", t: "Relevé de notes — L1", d: "", s: "", g: ["req"] },
      { id: "nl52", t: "Relevé de notes — L2", d: "", s: "", g: ["req"] },
      { id: "nl53", t: "Relevé de notes — L3", d: "", s: "", g: ["req"] },
      { id: "nl54", t: "Diplôme de Licence", d: "", s: "", g: ["req"] },
      { id: "nl55", t: "Relevé de notes — M1", d: "", s: "", g: ["req"] },
      { id: "nl56", t: "Relevé de notes — M2", d: "", s: "", g: ["req"] },
      { id: "nl57", t: "Diplôme de Master", d: "", s: "", g: ["req"] },
      {
        id: "nl58",
        t: "Annexe descriptive — Licence",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "nl59",
        t: "Annexe descriptive — Master",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "nl60", t: "Certificat TCF", d: "", s: "", g: ["req"] },
      { id: "nl61", t: "Papier de préinscription", d: "", s: "", g: ["req"] },
      { id: "nl62", t: "Bordereau de retrait", d: "", s: "", g: ["req"] },
      { id: "nl63", t: "Certificat de travail", d: "", s: "", g: ["req"] },
      { id: "nl64", t: "Lettres de recommandation", d: "", s: "", g: ["req"] },
      {
        id: "nl65",
        t: "Fiche familiale d'état civil",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl66",
        t: "Acte de naissance — moi",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl67",
        t: "Acte de naissance — mère",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl68",
        t: "Acte de naissance — père",
        d: "10 exemplaires",
        s: "",
        g: ["req"],
      },
      {
        id: "nl69",
        t: "Acte de naissance — grand-père",
        d: "⚠ quantité non précisée — à confirmer combien d'exemplaires",
        s: "",
        g: ["opt"],
      },
      { id: "nl70", t: "Carte Visa AGB", d: "", s: "", g: ["req"] },
      { id: "nl71", t: "Permis de conduire", d: "", s: "", g: ["req"] },
      {
        id: "nl72",
        t: "Copies de tous les relevés et diplômes",
        d: "Un jeu complet de copies séparé des originaux",
        s: "",
        g: ["req"],
      },
      { id: "nl73", t: "Photos d'identité", d: "20 photos", s: "", g: ["req"] },
      {
        id: "nl74",
        t: "Tous les documents scannés",
        d: "Sauvegarde cloud + clé USB, séparée du sac à documents",
        s: "",
        g: ["req"],
      },
      { id: "nl75", t: "Photo de famille", d: "", s: "", g: ["opt"] },
      {
        id: "nl150",
        t: "Porte-documents",
        d: "⚠ ajouté — pochette/classeur rigide pour garder les originaux à plat et protégés durant le voyage",
        s: "",
        g: ["req"],
      },
    ],
  },
  {
    id: "nl-docs-medicaux",
    ico: "🩺",
    bg: "#fff7e6",
    nm: "Dossier militaire & médical",
    badge: { t: "À emporter", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "nl76", t: "Radio EFR (asthme)", d: "", s: "", g: ["req"] },
      { id: "nl77", t: "Radio de l'épaule", d: "", s: "", g: ["req"] },
      { id: "nl78", t: "Papier de l'épaule", d: "", s: "", g: ["req"] },
      { id: "nl79", t: "Papier ophtalmo", d: "", s: "", g: ["req"] },
      { id: "nl80", t: "Ordonnance lunettes", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "nl-argent-admin",
    ico: "💳",
    bg: "#fff7e6",
    nm: "Argent & administratif",
    badge: { t: "⚠ ajouté", c: "b-pur" },
    note: {
      t: "Pas dans ta description d'origine — supprime avec le × si déjà réglé ou inutile.",
      c: "n-amb",
    },
    items: [
      {
        id: "nl151",
        t: "Argent liquide en euros",
        d: "Pour les premiers jours avant que la carte/le compte bancaire français fonctionne — quelques centaines d'euros habituellement conseillés",
        s: "",
        g: ["req"],
      },
      {
        id: "nl152",
        t: "Deuxième moyen de paiement (carte de secours)",
        d: "Au cas où la carte AGB pose problème à l'étranger",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl153",
        t: "Papiers d'assurance santé",
        d: "Distincte de l'assurance voyage AGB — à vérifier qu'elle couvre bien les soins courants en France",
        s: "",
        g: ["req"],
      },
      {
        id: "nl154",
        t: "Permis de conduire international",
        d: "Le permis algérien seul risque de ne pas suffire pour conduire durablement en France — à vérifier avant le départ",
        s: "",
        g: ["opt"],
      },
    ],
  },
  {
    id: "nl-fournitures",
    ico: "✏️",
    bg: "#eef2ff",
    nm: "Fournitures & petits objets",
    badge: { t: "⚠ ajouté", c: "b-pur" },
    note: {
      t: "Pas dans ta description d'origine — supprime avec le × si inutile.",
      c: "n-grn",
    },
    items: [
      { id: "nl155", t: "Cahier / carnet de cours", d: "", s: "", g: ["opt"] },
      { id: "nl156", t: "Stylos", d: "", s: "", g: ["opt"] },
      {
        id: "nl157",
        t: "Nécessaire de couture (mini kit)",
        d: "Bouton qui saute, ourlet — pratique sans avoir de couturier à proximité",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl158",
        t: "Quelques cintres",
        d: "Pour le Qamis et les vestes",
        s: "",
        g: ["opt"],
      },
    ],
  },
  {
    id: "nl-divers-suggeres",
    ico: "🧭",
    bg: "#eef2ff",
    nm: "Divers suggérés",
    badge: { t: "Vérifie si utile", c: "b-pur" },
    note: {
      t: "Pas dans ta description d'origine — supprime avec le × si inutile.",
      c: "n-grn",
    },
    items: [
      {
        id: "nl125",
        t: "Petite pharmacie (paracétamol, pansements)",
        d: "⚠ ajouté",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl126",
        t: "Parapluie",
        d: "⚠ ajouté — climat de Besançon",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl127",
        t: "Caleçons longs (sous-vêtement thermique)",
        d: "⚠ ajouté — utile pour l'hiver à Besançon",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl128",
        t: "Sajjada (tapis de prière)",
        d: "⚠ ajouté",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl129",
        t: "Cadenas",
        d: "⚠ ajouté — casiers/laverie résidence",
        s: "",
        g: ["opt"],
      },
      {
        id: "nl159",
        t: "Snacks / épices de chez soi",
        d: "⚠ ajouté — vérifier les règles de douane françaises avant d'en emporter",
        s: "",
        g: ["opt"],
      },
    ],
  },
];

export const BAGAGE_SECS = BAGAGE_SECS_v4;
export const ACHETER_SECS = [];

export const CHAPTERS_META = [
  { key: "bagages", label: "Bagages", data: BAGAGE_SECS },
  { key: "acheter", label: "Acheter", data: ACHETER_SECS },
];
