export const DEPART_SECS = [
  {
    id: "compl",
    ico: "📋",
    bg: "#fef9c3",
    nm: "Documents complémentaires — Militaire, médical, S1",
    badge: { t: "À rassembler", c: "b-amb" },
    note: {
      t: "Documents spécifiques à ta situation, en plus du dossier standard ci-dessus.",
      c: "n-amb",
    },
    items: [
      {
        id: "compl1",
        t: "Fiche familiale d'état civil — version française",
        d: "À demander directement en français à la commune de naissance",
        s: "L'Algérie et la France sont dispensées d'apostille pour les actes d'état civil (convention bilatérale du 27 août 1964 + protocole judiciaire de 1962). Demande la version bilingue/française directement au guichet pour éviter la traduction assermentée.",
        g: ["req"],
      },
      {
        id: "compl2",
        t: "Formulaire S1",
        d: "Si couverture sociale d'origine transférable",
        s: "À vérifier auprès de ta caisse actuelle — souvent non applicable pour un étudiant algérien hors UE/EEE/Suisse, mais à confirmer selon ton cas précis.",
        g: ["inf"],
      },
      {
        id: "compl3",
        t: "Dossier militaire — livret militaire / attestation de situation",
        d: "Souvent demandé au contrôle de sortie du territoire",
        s: "Se renseigner auprès du bureau du service national de ta commune pour l'attestation de position vis-à-vis du service national (position régulière, sursis ou dispense).",
        g: ["req"],
      },
      {
        id: "compl4",
        t: "Certificat médical ophtalmologique",
        d: "+ ordonnance lunettes/lentilles si tu en portes",
        s: "",
        g: ["req"],
      },
      {
        id: "compl5",
        t: "Certificat médical — épaule",
        d: "Bilan/compte-rendu du spécialiste, à jour",
        s: "Idéalement en français ou traduit. Garde une copie numérique pour ton futur médecin traitant en France.",
        g: ["req"],
      },
      {
        id: "compl6",
        t: "Dossier médical — asthme",
        d: "Traitement en cours, ordonnance, ventoline de secours",
        s: "À emporter dans le bagage à main, jamais en soute.",
        g: ["req"],
      },
    ],
  },
  {
    id: "planning",
    ico: "🗓️",
    bg: "#f0fdfa",
    nm: "Planning des 4 semaines avant le départ",
    badge: { t: "Compte à rebours", c: "b-pur" },
    note: {
      t: "Semaine par semaine, ce qu'il reste à faire avant le vol.",
      c: "n-pur",
    },
    items: [
      // Semaine 4
      {
        id: "plan1",
        t: "S4 — Réserver le vol",
        d: "Vérifier franchise bagages en soute + cabine",
        s: "",
        g: ["req"],
      },
      {
        id: "plan2",
        t: "S4 — Faire traduire l'acte de naissance si nécessaire",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan3",
        t: "S4 — Rassembler diplômes et relevés de notes originaux",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan4",
        t: "S4 — Confirmer fin de préavis Cirta Soft vs date de vol",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan5",
        t: "S4 — Continuer suivi CROUS + relance loge.GBM prévue en août",
        d: "",
        s: "",
        g: ["req"],
      },
      // Semaine 3
      {
        id: "plan6",
        t: "S3 — Souscrire assurance habitation dès logement confirmé",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan7",
        t: "S3 — Prévoir une assurance voyage temporaire",
        d: "Pour les premiers jours/semaines avant affiliation officielle",
        s: "",
        g: ["req"],
      },
      {
        id: "plan8",
        t: "S3 — Trier vêtements et commencer la valise",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan9",
        t: "S3 — Vérifier validité du passeport",
        d: "Minimum 6 mois après la date de retour prévue",
        s: "",
        g: ["req"],
      },
      {
        id: "plan10",
        t: "S3 — Sauvegarder toutes les copies numériques",
        d: "Cloud + clé USB, pas seulement le téléphone",
        s: "",
        g: ["req"],
      },
      // Semaine 2
      {
        id: "plan11",
        t: "S2 — Peser la valise",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan12",
        t: "S2 — Préparer la pochette documents cabine",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan13",
        t: "S2 — Informer la banque algérienne du départ",
        d: "",
        s: "",
        g: ["inf"],
      },
      {
        id: "plan14",
        t: "S2 — Activer eSIM ou forfait international temporaire",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan15",
        t: "S2 — Dernière relance loge.GBM si toujours sans logement",
        d: "",
        s: "",
        g: ["inf"],
      },
      // Semaine 1
      {
        id: "plan16",
        t: "S1 — Valise finale + pesée",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan17",
        t: "S1 — Vérifier que tous les originaux sont en bagage à main",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan18",
        t: "S1 — Imprimer réservation logement, attestation admission, billet, assurance",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan19",
        t: "S1 — Charger tous les appareils électroniques",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "plan20",
        t: "S1 — Vérifier la météo à Besançon pour ajuster la valise",
        d: "",
        s: "",
        g: ["inf"],
      },
    ],
  },
];

// ============================================================================
// Liste de bagages personnalisée — généré à partir de la description libre
// fournie. Remplace (ou complète) les exports BAGAGE_SECS / ACHETER_SECS
// dans src/data.js du projet React.
//
// Convention reprise de l'app :
//   g: ["req"]        -> obligatoire
//   g: ["opt"]        -> optionnel
//   g: ["inf"]        -> information
//   g: [..., "buy"]   -> à acheter (le ticket "à acheter" s'affiche,
//                         `est` = prix estimé en DA)
//
// Quelques points ambigus dans la description d'origine ont été tranchés
// avec l'hypothèse la plus raisonnable (marqués "⚠" dans les commentaires
// ci-dessous) — à corriger directement dans l'app avec le bouton 🛒 sur
// chaque ticket si besoin.
// ============================================================================

export const BAGAGE_SECS = [
  {
    id: "pk-vetements-emporter",
    ico: "👕",
    bg: "#eef2ff",
    nm: "Vêtements — déjà en ma possession",
    badge: { t: "Ne rien oublier", c: "b-blu" },
    note: {
      t: "Ce que j'ai déjà chez moi — à emballer.",
      c: "n-grn",
    },
    items: [
      { id: "pk1", t: "T-shirt bleu marine (navy)", d: "", s: "", g: ["req"] },
      { id: "pk2", t: "T-shirt beige", d: "", s: "", g: ["req"] },
      { id: "pk3", t: "T-shirt bleu et blanc", d: "", s: "", g: ["req"] },
      { id: "pk4", t: "Chemise bleu et blanc", d: "", s: "", g: ["req"] },
      { id: "pk5", t: "Doudoune noire", d: "", s: "", g: ["req"] },
      { id: "pk6", t: "Grosse veste (hiver)", d: "", s: "", g: ["req"] },
      { id: "pk7", t: "Veste mi-saison", d: "", s: "", g: ["req"] },
      { id: "pk8", t: "Veste noire de sport / training", d: "", s: "", g: ["req"] },
      { id: "pk9", t: "Casquette verte", d: "", s: "", g: ["opt"] },
      { id: "pk10", t: "Casquette bleue", d: "", s: "", g: ["opt"] },
      { id: "pk11", t: "Casquette bordeaux", d: "", s: "", g: ["opt"] },
      { id: "pk12", t: "Pantalon classique noir", d: "", s: "", g: ["req"] },
      {
        id: "pk13",
        t: "Baskets beige/caramel confort",
        d: "",
        s: "",
        g: ["req"],
      },
      {
        id: "pk14",
        t: "Bonnet",
        d: "⚠ à vérifier si déjà en ma possession — sinon à basculer côté achat",
        s: "",
        g: ["opt"],
      },
      {
        id: "pk15",
        t: "Gants",
        d: "⚠ à vérifier si déjà en ma possession — sinon à basculer côté achat",
        s: "",
        g: ["opt"],
      },
      {
        id: "pk16",
        t: "Brosse à dents",
        d: "⚠ à vérifier si déjà en ma possession — sinon à basculer côté achat",
        s: "",
        g: ["opt"],
      },
    ],
  },
  {
    id: "pk-electronique-emporter",
    ico: "💻",
    bg: "#eef2ff",
    nm: "Électronique — déjà en ma possession",
    badge: { t: "Vérifier avant de fermer la valise", c: "b-blu" },
    note: { t: "", c: "n-grn" },
    items: [
      {
        id: "pk17",
        t: "Chargeur laptop + adaptateur multiport",
        d: "Le multiport du chargeur, pas juste le câble",
        s: "",
        g: ["req"],
      },
      { id: "pk18", t: "Clé USB (flash disque)", d: "", s: "", g: ["req"] },
      {
        id: "pk19",
        t: "Écouteurs (1re paire, déjà en ma possession)",
        d: "Une 2e paire est à acheter en secours",
        s: "",
        g: ["req"],
      },
      { id: "pk20", t: "Portefeuille", d: "Un 2e est optionnel côté achat", s: "", g: ["req"] },
      { id: "pk21", t: "Cartable / sac à documents", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "pk-docs-admin-emporter",
    ico: "📄",
    bg: "#fff7e6",
    nm: "Documents administratifs — à emporter",
    badge: { t: "Original + copie + scan", c: "b-amb" },
    note: {
      t: "Chaque diplôme/relevé doit être emporté en original ET en copie, et scanné/sauvegardé (cloud + clé USB) avant le départ.",
      c: "n-amb",
    },
    items: [
      { id: "pk22", t: "Baccalauréat (original + copie)", d: "", s: "", g: ["req"] },
      { id: "pk23", t: "Relevé de notes du BAC", d: "", s: "", g: ["req"] },
      { id: "pk24", t: "Diplôme de Licence (original + copie)", d: "", s: "", g: ["req"] },
      { id: "pk25", t: "Relevé de notes Licence", d: "", s: "", g: ["req"] },
      { id: "pk26", t: "Annexe descriptive du diplôme de Licence", d: "", s: "", g: ["req"] },
      { id: "pk27", t: "Diplôme de Master (original + copie)", d: "", s: "", g: ["req"] },
      { id: "pk28", t: "Relevé de notes Master", d: "", s: "", g: ["req"] },
      { id: "pk29", t: "Annexe descriptive du diplôme de Master", d: "", s: "", g: ["req"] },
      { id: "pk30", t: "Classement de la promotion — Master 1", d: "", s: "", g: ["req"] },
      { id: "pk31", t: "Lettres de recommandation", d: "", s: "", g: ["req"] },
      { id: "pk32", t: "Certificat de travail (Cirta Soft)", d: "", s: "", g: ["req"] },
      { id: "pk33", t: "Fiche familiale d'état civil", d: "6 exemplaires", s: "", g: ["req"] },
      {
        id: "pk34",
        t: "Acte de naissance — moi",
        d: "6 à 8 exemplaires, format S12",
        s: "",
        g: ["req"],
      },
      {
        id: "pk35",
        t: "Acte de naissance — père",
        d: "6 à 8 exemplaires, format S12",
        s: "",
        g: ["req"],
      },
      {
        id: "pk36",
        t: "Acte de naissance — mère",
        d: "6 à 8 exemplaires, format S12",
        s: "",
        g: ["req"],
      },
      { id: "pk37", t: "Permis de conduire", d: "", s: "", g: ["req"] },
      { id: "pk38", t: "Carte Visa AGB", d: "", s: "", g: ["req"] },
      {
        id: "pk39",
        t: "Passeport + 12 photos d'identité",
        d: "",
        s: "",
        g: ["req"],
      },
      { id: "pk40", t: "Papier de préinscription (UMLP Besançon)", d: "", s: "", g: ["req"] },
      { id: "pk41", t: "Bordereau de retrait", d: "", s: "", g: ["req"] },
    ],
  },
  {
    id: "pk-docs-medicaux-emporter",
    ico: "🩺",
    bg: "#fff7e6",
    nm: "Documents médicaux — à emporter",
    badge: { t: "Pour dossier / suivi en France", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "pk42", t: "Papier militaire", d: "", s: "", g: ["req"] },
      { id: "pk43", t: "Radio + rapport épaule", d: "", s: "", g: ["req"] },
      { id: "pk44", t: "Papier asthme", d: "", s: "", g: ["req"] },
      { id: "pk45", t: "Radio EFR (fonction respiratoire)", d: "", s: "", g: ["req"] },
      { id: "pk46", t: "Rapport ophtalmo", d: "", s: "", g: ["req"] },
      { id: "pk47", t: "Ordonnance lunettes", d: "", s: "", g: ["req"] },
    ],
  },
];

export const ACHETER_SECS = [
  {
    id: "pk-vetements-acheter",
    ico: "👕",
    bg: "#fff1f0",
    nm: "Vêtements — à acheter",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "pk50", t: "T-shirt noir", d: "", s: "", g: ["buy"], est: 1500 },
      { id: "pk51", t: "T-shirt blanc", d: "", s: "", g: ["buy"], est: 1500 },
      { id: "pk52", t: "Pantalon noir (1/2)", d: "", s: "", g: ["buy"], est: 4000 },
      { id: "pk53", t: "Pantalon noir (2/2)", d: "", s: "", g: ["buy"], est: 4000 },
      { id: "pk54", t: "Pantalon beige/caramel", d: "", s: "", g: ["buy"], est: 4000 },
      {
        id: "pk55",
        t: "Pantalon couleur à définir",
        d: "⚠ couleur non précisée — à choisir en magasin",
        s: "",
        g: ["buy"],
        est: 4000,
      },
      { id: "pk56", t: "Chemise blanche", d: "", s: "", g: ["buy"], est: 3500 },
      {
        id: "pk57",
        t: "Chemise couleur à définir",
        d: "⚠ couleur non précisée — à choisir en magasin",
        s: "",
        g: ["buy"],
        est: 3500,
      },
      { id: "pk58", t: "Sous-vêtements (lot de 8)", d: "", s: "", g: ["buy"], est: 3000 },
      {
        id: "pk59",
        t: "Maillots de corps / t-shirts en dessous (lot de 5)",
        d: "",
        s: "",
        g: ["buy"],
        est: 2500,
      },
      {
        id: "pk60",
        t: "Tenue de sport (t-shirt + jogging)",
        d: "",
        s: "",
        g: ["buy"],
        est: 4500,
      },
      { id: "pk61", t: "Baskets blanches", d: "", s: "", g: ["buy"], est: 6000 },
      {
        id: "pk62",
        t: "Baskets (3e paire)",
        d: "⚠ modèle/couleur non précisés",
        s: "",
        g: ["buy"],
        est: 6000,
      },
      { id: "pk63", t: "Chaussettes normales (lot de 6)", d: "", s: "", g: ["buy"], est: 1500 },
      { id: "pk64", t: "Chaussettes longues (lot de 2)", d: "", s: "", g: ["buy"], est: 800 },
      { id: "pk65", t: "Chaussettes autres (lot de 4)", d: "", s: "", g: ["buy"], est: 1200 },
      { id: "pk66", t: "Short", d: "", s: "", g: ["buy"], est: 2000 },
      { id: "pk67", t: "Pyjama", d: "", s: "", g: ["buy"], est: 2500 },
      {
        id: "pk68",
        t: "Kamis",
        d: "Tenue traditionnelle pour l'Aïd",
        s: "",
        g: ["buy"],
        est: 6000,
      },
      {
        id: "pk69",
        t: "Pantalon classique large (optionnel)",
        d: "Si trouvé — non prioritaire",
        s: "",
        g: ["buy"],
        est: 4000,
      },
      { id: "pk70", t: "Bonnet", d: "Si pas déjà en ma possession", s: "", g: ["buy"], est: 1000 },
      { id: "pk71", t: "Gants", d: "Si pas déjà en ma possession", s: "", g: ["buy"], est: 1200 },
    ],
  },
  {
    id: "pk-hygiene-acheter",
    ico: "🧴",
    bg: "#fff1f0",
    nm: "Hygiène & soins — à acheter",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "pk80", t: "Déodorant stick", d: "", s: "", g: ["buy"], est: 800 },
      { id: "pk81", t: "Gel douche", d: "", s: "", g: ["buy"], est: 900 },
      { id: "pk82", t: "Shampooing", d: "", s: "", g: ["buy"], est: 900 },
      { id: "pk83", t: "Après-shampooing", d: "", s: "", g: ["buy"], est: 900 },
      {
        id: "pk84",
        t: "Tondeuse à cheveux",
        d: "",
        s: "",
        g: ["buy"],
        est: 5000,
      },
      {
        id: "pk85",
        t: "Rasoir type coiffeur/barbier",
        d: "Rasoir manuel professionnel",
        s: "",
        g: ["buy"],
        est: 1500,
      },
      { id: "pk86", t: "Rasoirs jetables (2 paquets)", d: "", s: "", g: ["buy"], est: 1200 },
      { id: "pk87", t: "Masque cheveux", d: "", s: "", g: ["buy"], est: 1200 },
      { id: "pk88", t: "Crème cheveux (coiffante)", d: "", s: "", g: ["buy"], est: 900 },
      { id: "pk89", t: "Gel cheveux", d: "", s: "", g: ["buy"], est: 700 },
      {
        id: "pk90",
        t: "Crème dépilatoire corps (lot de 3)",
        d: "",
        s: "",
        g: ["buy"],
        est: 2400,
      },
      { id: "pk91", t: "Coupe-ongles", d: "", s: "", g: ["buy"], est: 400 },
      { id: "pk92", t: "Ciseaux", d: "", s: "", g: ["buy"], est: 500 },
      { id: "pk93", t: "Brosse à cheveux (ronde/brushing)", d: "", s: "", g: ["buy"], est: 900 },
      { id: "pk94", t: "Brosse à cheveux normale", d: "", s: "", g: ["buy"], est: 600 },
      { id: "pk95", t: "Parfum", d: "", s: "", g: ["buy"], est: 4000 },
      {
        id: "pk96",
        t: "Recharges parfum/déodorant (3 à 4)",
        d: "",
        s: "",
        g: ["buy"],
        est: 3000,
      },
      { id: "pk97", t: "Crème Cilane bio", d: "", s: "", g: ["buy"], est: 1800 },
      { id: "pk98", t: "Gel nettoyant visage", d: "", s: "", g: ["buy"], est: 1200 },
      { id: "pk99", t: "Pansements", d: "", s: "", g: ["buy"], est: 400 },
      {
        id: "pk100",
        t: "Médicament contre les maux de tête",
        d: "",
        s: "",
        g: ["buy"],
        est: 500,
      },
      { id: "pk101", t: "Kassa (gant de kessa)", d: "", s: "", g: ["buy"], est: 300 },
      { id: "pk102", t: "Serviette de corps", d: "", s: "", g: ["buy"], est: 1500 },
      { id: "pk103", t: "Serviette de visage", d: "", s: "", g: ["buy"], est: 700 },
      {
        id: "pk104",
        t: "Sèchoir à cheveux",
        d: "Optionnel, si possible",
        s: "",
        g: ["buy"],
        est: 3500,
      },
    ],
  },
  {
    id: "pk-electronique-acheter",
    ico: "🔌",
    bg: "#fff1f0",
    nm: "Électronique — à acheter",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      {
        id: "pk110",
        t: "Écouteurs (2e paire / secours)",
        d: "",
        s: "",
        g: ["buy"],
        est: 2500,
      },
      { id: "pk111", t: "Casque audio", d: "", s: "", g: ["buy"], est: 6000 },
      {
        id: "pk112",
        t: "Disque dur externe 1To",
        d: "Optionnel",
        s: "",
        g: ["buy"],
        est: 9000,
      },
      {
        id: "pk113",
        t: "Adaptateur prise (3 broches → 2 broches, EU)",
        d: "Pour le chargeur laptop",
        s: "",
        g: ["buy"],
        est: 800,
      },
      { id: "pk114", t: "Power bank", d: "", s: "", g: ["buy"], est: 4000 },
    ],
  },
  {
    id: "pk-bagages-acheter",
    ico: "🧳",
    bg: "#fff1f0",
    nm: "Bagages (valises) — à acheter",
    badge: { t: "Norme Air Algérie", c: "b-amb" },
    note: {
      t: "Norme bagages Air Algérie (classe économique, vol international) : 1 bagage en soute jusqu'à 23 kg + 1 bagage cabine jusqu'à 10 kg. À reconfirmer sur le billet exact avant l'achat des valises (le poids autorisé peut varier selon la destination/tarif).",
      c: "n-amb",
    },
    items: [
      {
        id: "pk120",
        t: "Valise soute — 23 kg",
        d: "Vérifier les dimensions max autorisées par Air Algérie",
        s: "",
        g: ["buy"],
        est: 8000,
      },
      {
        id: "pk121",
        t: "Sac cabine — 10 kg",
        d: "Vérifier les dimensions max autorisées par Air Algérie",
        s: "",
        g: ["buy"],
        est: 4000,
      },
    ],
  },
  {
    id: "pk-divers-acheter",
    ico: "✏️",
    bg: "#fff1f0",
    nm: "Divers — à acheter",
    badge: { t: "À acheter avant le départ", c: "b-amb" },
    note: { t: "", c: "n-amb" },
    items: [
      { id: "pk130", t: "Carnet / journal", d: "", s: "", g: ["buy"], est: 600 },
      { id: "pk131", t: "Cahier de croquis (sketchbook)", d: "", s: "", g: ["buy"], est: 900 },
      { id: "pk132", t: "Stylo bleu", d: "", s: "", g: ["buy"], est: 100 },
      { id: "pk133", t: "Stylo noir", d: "", s: "", g: ["buy"], est: 100 },
      { id: "pk134", t: "Crayon à papier", d: "", s: "", g: ["buy"], est: 100 },
      {
        id: "pk135",
        t: "Gomme",
        d: "⚠ interprété depuis « arrasor » — à corriger si ce n'était pas ça",
        s: "",
        g: ["buy"],
        est: 100,
      },
      { id: "pk136", t: "Sajjada (tapis de prière)", d: "", s: "", g: ["buy"], est: 2500 },
      { id: "pk137", t: "Lunettes de soleil", d: "", s: "", g: ["buy"], est: 3000 },
      {
        id: "pk138",
        t: "Lunettes de vue (médicales)",
        d: "Selon l'ordonnance",
        s: "",
        g: ["buy"],
        est: 8000,
      },
      { id: "pk139", t: "Crème solaire", d: "", s: "", g: ["buy"], est: 1500 },
      {
        id: "pk140",
        t: "Portefeuille (2e, optionnel)",
        d: "",
        s: "",
        g: ["buy"],
        est: 2000,
      },
    ],
  },
];

// export const BAGAGE_SECS = [
//   {
//     id: "valise-emporter",
//     ico: "🎒",
//     bg: "#eef2ff",
//     nm: "Bagages — à emporter (déjà en ma possession)",
//     badge: { t: "Ne rien oublier", c: "b-blu" },
//     note: {
//       t: "Ce que j'ai déjà chez moi — coche chaque élément une fois emballé dans la valise, pour ne rien oublier le jour du départ.",
//       c: "n-grn",
//     },
//     items: [
//       {
//         id: "val3",
//         t: "Pulls / sweats chauds (3-4)",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val4",
//         t: "T-shirts / hauts manches longues (5-7)",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val5",
//         t: "Pantalons du quotidien (2-3) + 1 jean",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val6",
//         t: "Sous-vêtements et chaussettes chaudes",
//         d: "Prévoir 10-14 jours d'avance",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val7",
//         t: "Chaussures fermées imperméables + baskets + chaussons",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val9",
//         t: "Tenue correcte pour entretiens",
//         d: "Utile pour les entretiens d'alternance",
//         s: "",
//         g: ["inf"],
//       },
//       {
//         id: "val10",
//         t: "Trousse de toilette de base",
//         d: "Le reste s'achète facilement sur place",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val11",
//         t: "Médicaments personnels + copies d'ordonnances",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val14",
//         t: "Laptop + housse + casque/écouteurs",
//         d: "",
//         s: "",
//         g: ["req"],
//       },
//       {
//         id: "val18",
//         t: "Sac à dos cours, nécessaire de couture, photos famille",
//         d: "Et snacks/épices non périssables si envie de chez soi (vérifier douane)",
//         s: "",
//         g: ["inf"],
//       },
//     ],
//   },
// ];

// export const ACHETER_SECS = [
//   {
//     id: "valise-acheter",
//     ico: "🛒",
//     bg: "#fff1f0",
//     nm: "Bagages — à acheter avant le départ",
//     badge: { t: "~220€ estimé", c: "b-amb" },
//     note: {
//       t: "Ce qu'il reste à acheter avant le départ. Chaque ligne est reprise dans l'onglet Budget avec un coût estimé — coche « acheté » une fois fait, ça remplit automatiquement le coût réel (modifiable ensuite dans Budget).",
//       c: "n-amb",
//     },
//     items: [
//       {
//         id: "val1",
//         t: "Manteau chaud / doudoune hiver",
//         d: "Climat continental à Besançon : froid dès novembre",
//         s: "",
//         g: ["buy"],
//         est: 80,
//       },
//       {
//         id: "val2",
//         t: "Veste mi-saison imperméable",
//         d: "",
//         s: "",
//         g: ["buy"],
//         est: 40,
//       },
//       {
//         id: "val8",
//         t: "Écharpe, bonnet, gants",
//         d: "L'hiver arrive vite en Franche-Comté",
//         s: "",
//         g: ["buy"],
//         est: 25,
//       },
//       {
//         id: "val12",
//         t: "Petite pharmacie de secours",
//         d: "Paracétamol, pansements, etc.",
//         s: "",
//         g: ["buy"],
//         est: 15,
//       },
//       {
//         id: "val13",
//         t: "Chargeurs + adaptateur de prise + batterie externe",
//         d: "Batterie externe : cabine uniquement",
//         s: "",
//         g: ["buy"],
//         est: 20,
//       },
//       {
//         id: "val15",
//         t: "Serviette de bain",
//         d: "Utile les premiers jours avant équipement complet",
//         s: "",
//         g: ["buy"],
//         est: 10,
//       },
//       {
//         id: "val16",
//         t: "Drap housse / taie d'oreiller",
//         d: "Si logement non meublé en linge",
//         s: "",
//         g: ["buy"],
//         est: 20,
//       },
//       {
//         id: "val17",
//         t: "Cadenas",
//         d: "Si résidence avec casiers/laverie commune",
//         s: "",
//         g: ["buy"],
//         est: 10,
//       },
//     ],
//   },
// ];

export const AFTER_SECS = [
  {
    id: "vlsts",
    ico: "🌐",
    bg: "#eff6ff",
    nm: "Validation VLS-TS — Dans les 3 mois après arrivée",
    badge: { t: "OBLIGATOIRE dans 3 mois", c: "b-red" },
    note: {
      t: "Si tu ne valides pas ton VLS-TS dans les 3 mois après l'arrivée, tu es en situation irrégulière. C'est une démarche en ligne rapide.",
      c: "n-red",
    },
    items: [
      {
        id: "a1",
        t: "Valider le VLS-TS sur le portail ANEF",
        d: "Démarche en ligne obligatoire dès l'arrivée en France (dans les 3 mois max).",
        s: '<b>1. Aller sur :</b> <a href="https://administration-etrangers-en-france.interieur.gouv.fr" target="_blank">administration-etrangers-en-france.interieur.gouv.fr</a><br><b>2. Créer un compte</b> avec ton email<br><b>3. Saisir</b> les informations de ton visa<br><b>4. Justificatif de domicile en France</b> (adresse hôtel au début)<br><b>5. Payer</b> taxe ≈ 50€ (carte bancaire ou timbre fiscal en bureau de tabac)<br><b>6. Conserver</b> l\'attestation de validation',
        g: ["req", "Dès arrivée"],
      },
    ],
  },
  {
    id: "cvec",
    ico: "💳",
    bg: "#f0fdf4",
    nm: "CVEC — Avant l'inscription universitaire",
    badge: { t: "~103€ obligatoire", c: "b-amb" },
    items: [
      {
        id: "a2",
        t: "Payer la Contribution Vie Étudiante et de Campus",
        d: "Obligatoire avant toute inscription à l'université. Si boursier CROUS : exonération totale.",
        s: '<b>1. Aller sur :</b> <a href="https://cvec.etudiant.gouv.fr" target="_blank">cvec.etudiant.gouv.fr</a><br><b>2. Créer un compte</b> avec ton INE (fourni par l\'université)<br><b>3. Payer</b> en ligne par carte bancaire (≈ 103€)<br><b>4. Télécharger l\'attestation CVEC</b> → présenter au service des inscriptions',
        g: ["req", "Avant inscription"],
      },
    ],
  },
  {
    id: "crous",
    ico: "🏠",
    bg: "#f5f3ff",
    nm: "CROUS Besançon — Demande de logement (7 juillet)",
    badge: { t: "7 juillet 2025", c: "b-pur" },
    note: {
      t: "<b>Phase complémentaire :</b> ouverte à TOUS les étudiants (y compris internationaux sans DSE) à partir du 7 juillet. Aucun DSE requis. Les places se remplissent vite — connecte-toi le 7 juillet matin.",
      c: "n-pur",
    },
    items: [
      {
        id: "a3",
        t: "Créer ton compte MesServices.etudiant.gouv.fr (dès maintenant)",
        d: "Plateforme nationale pour logement, bourse, et toutes démarches étudiantes.",
        s: '<b>Maintenant :</b> <a href="https://messervices.etudiant.gouv.fr" target="_blank">messervices.etudiant.gouv.fr</a> → créer un compte avec ton email. Avoir le compte prêt accélère la démarche le 7 juillet.',
        g: ["req", "Maintenant"],
      },
      {
        id: "a4",
        t: "Le 7 juillet — se connecter sur trouverunlogement.lescrous.fr",
        d: "Phase complémentaire ouverte à tous. Filtrer par ville : Besançon, CROUS Bourgogne-Franche-Comté.",
        s: '<b>7 juillet matin :</b> <a href="https://trouverunlogement.lescrous.fr" target="_blank">trouverunlogement.lescrous.fr</a><br>→ Ville : Besançon | Type : chambre individuelle ou studio<br>→ Résidence Planoise (4 Place de l\'Europe, 25000 Besançon) : à partir de 340€/mois CC<br><b>Faire jusqu\'à 10 vœux</b> pour maximiser les chances.',
        g: ["req", "7 juillet"],
      },
      {
        id: "a5",
        t: "Documents à préparer pour la candidature CROUS",
        d: "À avoir prêts pour confirmer rapidement si une proposition est faite.",
        s: "<b>Documents demandés à l'entrée :</b><br>- Passeport + visa<br>- Attestation d'inscription universitaire (Besançon)<br>- RIB d'un compte bancaire FRANÇAIS<br>- Justificatif de ressources ou attestation garant<br>- <b>Assurance habitation obligatoire</b> (Maif Étudiant, Luko — en ligne en 10 min)",
        g: ["req"],
      },
      {
        id: "a6",
        t: "Alternative si CROUS complet — logements privés",
        d: "Options de repli si aucune chambre CROUS n'est disponible à Besançon.",
        s: '→ <a href="https://www.lokaviz.fr" target="_blank">lokaviz.fr</a> : annonces particuliers via CROUS<br>→ Le Bon Coin → "location meublé Besançon" (250–500€/mois studios)<br>→ <a href="https://www.appartager.com" target="_blank">appartager.com</a> : colocation Besançon<br>→ Résidences privées : Arpej, Nexity Studéa Besançon<br>→ Facebook : "Logement étudiant Besançon", "Étudiants UFC Besançon"',
        g: ["inf"],
      },
    ],
  },
  {
    id: "france",
    ico: "🏦",
    bg: "#fff7ed",
    nm: "Compte bancaire + CAF + Sécu + Carte de séjour",
    badge: { t: "Dès l'arrivée", c: "b-amb" },
    items: [
      {
        id: "a7",
        t: "Ouvrir un compte bancaire en France",
        d: "Nécessaire pour : payer le loyer, recevoir la CAF, être payé si tu travailles.",
        s: "<b>Options faciles pour étudiant étranger :</b><br>→ <b>La Banque Postale :</b> bureau de poste, accessible avec passeport + visa<br>→ <b>Boursorama / Revolut / Nickel :</b> 100% en ligne, avec passeport + selfie<br>→ <b>BNP / Société Générale :</b> en agence avec visa étudiant + justif. domicile + attestation inscription",
        g: ["req", "Dès arrivée"],
      },
      {
        id: "a8",
        t: "CAF — Aide Personnalisée au Logement (APL)",
        d: "100 à 300€/mois d'aide selon logement. Accessible avec visa étudiant valide.",
        s: '<b>Après avoir signé un bail :</b><br>1. <a href="https://www.caf.fr" target="_blank">caf.fr</a> → Créer un compte → Demander les APL<br>2. Joindre : RIB français, bail signé, passeport, visa, attestation inscription<br><b>Délai :</b> 1–2 mois pour le premier versement. Rétroactif dès le dépôt.',
        g: ["req", "Après bail signé"],
      },
      {
        id: "a9",
        t: "Sécurité Sociale étudiante (CPAM)",
        d: "Gratuite et obligatoire pour étudiants étrangers non-européens. Remplace l'assurance privée.",
        s: '<b>Lors de l\'inscription universitaire :</b> l\'université guidera vers la procédure CPAM. Ou directement :<br><a href="https://www.ameli.fr" target="_blank">ameli.fr</a> → "Étudiant étranger" → s\'affilier.<br><b>Documents :</b> passeport, visa, attestation inscription, justificatif domicile France.<br><b>Délai :</b> 2–4 semaines pour la carte Vitale.',
        g: ["req", "À l'inscription"],
      },
      {
        id: "a10",
        t: "Carte de séjour — Préfecture du Doubs (spécifique Algériens)",
        d: "En tant qu'Algérien, tu dois demander une carte de séjour à la préfecture (accord 1968).",
        s: '<b>Où :</b> Préfecture du Doubs, 8–10 rue Charles Nodier, 25000 Besançon.<br><b>RDV en ligne :</b> doubs.gouv.fr → "Titre de séjour" → prendre RDV.<br><b>Documents :</b> passeport + visa + justificatif domicile Besançon + attestation inscription + photos identité.<br><b>Faire cette démarche dans les 2 premiers mois après l\'arrivée.</b>',
        g: ["req", "Premiers mois"],
      },
    ],
  },
];

export const CHAPTERS_META = [
  { key: "depart", label: "Départ", data: DEPART_SECS },
  { key: "bagages", label: "Bagages", data: BAGAGE_SECS },
  { key: "acheter", label: "Acheter", data: ACHETER_SECS },
  { key: "after", label: "Après", data: AFTER_SECS },
];
